name: booking-order-app
services:
  field-service:
    container_name: field-service
    image: ranggad/field-service:1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env